CREATE TABLE STUDENTS (
SID INT NOT NULL,
FIRSTT VARCHAR(30) NOT NULL,
LASTT VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30),
primary key (SID)
);


CREATE TABLE EXERCISES (
CAT VARCHAR(30) NOT NULL,
ENO INT NOT NULL,
TOPIC VARCHAR(30),
MAXPT INT,
primary key(CAT,ENO)
);



CREATE TABLE RESULTS (
SID INT NOT NULL,
CAT VARCHAR(30) NOT NULL,
ENO INT NOT NULL,
POINTS INT,
FOREIGN KEY (SID) REFERENCES STUDENTS(SID),
FOREIGN KEY (CAT,ENO) REFERENCES EXERCISES(CAT,ENO)
);

INSERT INTO STUDENTS VALUES(101,’Ann’,’Smith’,’...’);
INSERT INTO STUDENTS VALUES(102,’Michel’,’Jones’,NULL);
INSERT INTO STUDENTS VALUES(103,’Richard’,’Tuner’,’...’);
INSERT INTO STUDENTS VALUES(104,’Maria’,’Brown’,’...’);

INSERT INTO EXERCISES VALUES(‘H’,1,’Rel.Alg’,10);
INSERT INTO EXERCISES VALUES(‘H’,2,’SQL’,10);
INSERT INTO EXERCISES VALUES(‘M’,1,’SQL.Alg’,14);

INSERT INTO RESULTS VALUES(101,’H’,1,10);
INSERT INTO RESULTS VALUES(101,’H’,2,8);
INSERT INTO RESULTS VALUES(101,’M’,1,12);
INSERT INTO RESULTS VALUES(102,’H’,1,9);
INSERT INTO RESULTS VALUES(102,’H’,2,9);
INSERT INTO RESULTS VALUES(102,’M’,1,10);
INSERT INTO RESULTS VALUES(103,’H’,1,5);
INSERT INTO RESULTS VALUES(103,’M’,1,7);




